runtime: php55
api_version: 1

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\.git$

handlers:
- url: /resources
  static_dir: web/resources
# the symfony front controller
- url: /.*
  script: web/index.php
