runtime: php55
api_version: 1

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\.git$

handlers:
# the symfony front controller
- url: /.*
  script: web/index.php
